//! Cross-implementation parity: the closed-form Rust HSiKAN op vs the **real**
//! PyTorch `SignedKANLayer` (spline_kind="catmull_rom", inner_skip="highway",
//! outer_skip="none", S=2).
//!
//! Fixture generated by `scripts/dev/hsikan_parity_fixture.py` on kato15's torch
//! env — a float64 reference. The Rust op is f32, so we compare at tol 1e-3: a
//! *structural* mismatch (wrong gather/gate/mask/mean/outer) would exceed it by
//! orders of magnitude, while f32 rounding stays well under. The fixture stores
//! the Chebyshev coefficients the Rust op consumes; the PyTorch layer was driven
//! with the CR control points those coefficients generate (an exact mapping,
//! since `chebyshev_cr == catmull_rom(chebyshev_control_points)` and both CR
//! evaluators are bit-identical). Regenerate only after an intentional change.

use holonomy_learn::{hsikan_forward, HsikanConfig, HsikanEdges, HsikanParams};

struct Case {
    arity: usize,
    n_edges: usize,
    vertices: Vec<u32>,
    signs: Vec<i8>,
    h_e: Vec<f32>,
}

struct Fixture {
    d: usize,
    grid: usize,
    cheb_k: usize,
    n_branches: usize,
    inner_coef: Vec<f32>,
    outer_coef: Vec<f32>,
    gate_w: Vec<f32>,
    gate_b: Vec<f32>,
    x: Vec<f32>,
    cases: Vec<Case>,
}

fn scalar(rest: &str) -> usize {
    rest.split_whitespace().next().unwrap().parse().unwrap()
}
fn floats(rest: &str) -> Vec<f32> {
    rest.split_whitespace()
        .map(|t| t.parse().unwrap())
        .collect()
}
fn u32s(rest: &str) -> Vec<u32> {
    rest.split_whitespace()
        .map(|t| t.parse().unwrap())
        .collect()
}
fn i8s(rest: &str) -> Vec<i8> {
    rest.split_whitespace()
        .map(|t| t.parse().unwrap())
        .collect()
}

fn parse(text: &str) -> Fixture {
    let (mut d, mut grid, mut cheb_k, mut n_branches) = (0, 0, 0, 0);
    let (mut inner_coef, mut outer_coef) = (Vec::new(), Vec::new());
    let (mut gate_w, mut gate_b, mut x) = (Vec::new(), Vec::new(), Vec::new());
    let mut cases: Vec<Case> = Vec::new();
    let mut cur: Option<Case> = None;
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let (key, rest) = line.split_once(' ').unwrap_or((line, ""));
        match key {
            "d" => d = scalar(rest),
            "grid" => grid = scalar(rest),
            "cheb_k" => cheb_k = scalar(rest),
            "n_branches" => n_branches = scalar(rest),
            "x" => x = floats(rest),
            "inner_coef" => inner_coef = floats(rest),
            "outer_coef" => outer_coef = floats(rest),
            "gate_w" => gate_w = floats(rest),
            "gate_b" => gate_b = floats(rest),
            "case_arity" => {
                if let Some(c) = cur.take() {
                    cases.push(c);
                }
                cur = Some(Case {
                    arity: scalar(rest),
                    n_edges: 0,
                    vertices: Vec::new(),
                    signs: Vec::new(),
                    h_e: Vec::new(),
                });
            }
            "case_n_edges" => cur.as_mut().unwrap().n_edges = scalar(rest),
            "case_vertices" => cur.as_mut().unwrap().vertices = u32s(rest),
            "case_signs" => cur.as_mut().unwrap().signs = i8s(rest),
            "case_h_e" => cur.as_mut().unwrap().h_e = floats(rest),
            _ => {}
        }
    }
    if let Some(c) = cur.take() {
        cases.push(c);
    }
    Fixture {
        d,
        grid,
        cheb_k,
        n_branches,
        inner_coef,
        outer_coef,
        gate_w,
        gate_b,
        x,
        cases,
    }
}

#[test]
fn matches_pytorch_signedkan_layer() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/hsikan_torch_parity.txt"
    );
    let text = std::fs::read_to_string(path)
        .expect("parity fixture present (regenerate via scripts/dev/hsikan_parity_fixture.py)");
    let fx = parse(&text);
    assert!(!fx.cases.is_empty(), "no cases parsed");

    let params = HsikanParams {
        inner_coef: &fx.inner_coef,
        outer_coef: &fx.outer_coef,
        gate_w: &fx.gate_w,
        gate_b: &fx.gate_b,
    };
    let mut max_diff = 0.0f32;
    for case in &fx.cases {
        let cfg = HsikanConfig::new(
            case.n_edges,
            case.arity,
            fx.d,
            fx.n_branches,
            fx.grid,
            fx.cheb_k,
            true,
        );
        let edges = HsikanEdges {
            vertices: &case.vertices,
            signs: &case.signs,
        };
        let (h_e, _) = hsikan_forward(params, &fx.x, edges, cfg);
        assert_eq!(h_e.len(), case.h_e.len());
        for (got, want) in h_e.iter().zip(&case.h_e) {
            let diff = (got - want).abs();
            max_diff = max_diff.max(diff);
            assert!(
                diff < 1e-3,
                "arity={} parity mismatch: got {got} want {want} (|Δ|={diff:.2e})",
                case.arity
            );
        }
    }
    eprintln!(
        "HSiKAN parity: max|Δ| = {max_diff:.2e} over {} arities",
        fx.cases.len()
    );
}
