//! Cross-implementation parity: the closed-form Rust spectral-entropy op vs the
//! **real** PyTorch `EntropyRegulariser` (autograd) on a fixed matrix.
//!
//! Fixture generated by `scripts/dev/spectral_entropy_fixture.py` on kato15's torch
//! env — a float64 reference (reg value + autograd ∇_A). The Rust op is f32 with a
//! Jacobi eigensolver; torch uses eigvalsh — but the eigenvalues agree and
//! ∇_A = 2·A·U diag(w)Uᵀ is eigenvector-basis-invariant, so parity is exact up to
//! f32 precision. We drive the Rust op with `lam_eff = lam_0` (the first-call value,
//! KL=0). Regenerate only after an intentional change.

use holonomy_learn::{spectral_reg_value_grad, SpectralEntropyConfig};

fn scalar_f32(rest: &str) -> f32 {
    rest.split_whitespace().next().unwrap().parse().unwrap()
}
fn scalar_usize(rest: &str) -> usize {
    rest.split_whitespace().next().unwrap().parse().unwrap()
}
fn floats(rest: &str) -> Vec<f32> {
    rest.split_whitespace()
        .map(|t| t.parse().unwrap())
        .collect()
}

#[test]
fn matches_pytorch_entropy_regulariser() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/spectral_entropy.txt"
    );
    let text = std::fs::read_to_string(path)
        .expect("fixture present (regenerate via scripts/dev/spectral_entropy_fixture.py)");

    let (mut n, mut d) = (0usize, 0usize);
    let (mut lam_0, mut lam_a, mut lam_b, mut lam_kl) = (0f32, 0f32, 0f32, 0f32);
    let (mut eta, mut target, mut reg_ref) = (0f32, 0f32, 0f32);
    let (mut a, mut grad_ref) = (Vec::new(), Vec::new());
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let (key, rest) = line.split_once(' ').unwrap_or((line, ""));
        match key {
            "n" => n = scalar_usize(rest),
            "d" => d = scalar_usize(rest),
            "lam_0" => lam_0 = scalar_f32(rest),
            "lam_a" => lam_a = scalar_f32(rest),
            "lam_b" => lam_b = scalar_f32(rest),
            "lam_kl" => lam_kl = scalar_f32(rest),
            "eta" => eta = scalar_f32(rest),
            "target" => target = scalar_f32(rest),
            "reg" => reg_ref = scalar_f32(rest),
            "a" => a = floats(rest),
            "grad" => grad_ref = floats(rest),
            _ => {}
        }
    }

    let cfg = SpectralEntropyConfig {
        lam_0,
        lam_a,
        lam_b,
        lam_kl,
        eta,
        target,
        eps: 1e-12,
        kl_normalized: false,
        momentum: 0.0,
    };
    // First call ⇒ lam_eff = lam_0.
    let (reg, grad, _h) = spectral_reg_value_grad(&a, n, d, &cfg, lam_0);

    assert!(
        (reg - reg_ref).abs() < 1e-4,
        "reg parity: {reg} vs {reg_ref}"
    );
    assert_eq!(grad.len(), grad_ref.len());
    let mut max_diff = 0.0f32;
    for (got, want) in grad.iter().zip(&grad_ref) {
        max_diff = max_diff.max((got - want).abs());
    }
    assert!(max_diff < 1e-3, "grad parity max|Δ| = {max_diff:.2e}");
    eprintln!(
        "spectral-entropy parity: reg |Δ|={:.2e}  grad max|Δ|={max_diff:.2e}",
        (reg - reg_ref).abs()
    );
}
